kernelsauce/turbo

turbo/websocket.lua

In websocket api, if payload>=126 then payload length is incorrectly computed. 
Stems from the lines 212-213 in websocket.lua: 
in function "_frame_len_16(data)", data is string type so;
ffi.cast("uint16_t", data) casts data's address instead of the value pointed that address.
Have not tested but the same should be true for the following function "_frame_len_64(data)"

fix in websocket.lua

---

turbo/async.lua

Websocket client using wss://host:8888 URL would use port 443 anyway.

Fix websocket client over SSL using other then standard port 443

---

Makefile
turbo/crypto_linux.lua
turbo/httputil.lua
turbo/util.lua
turbo/websocket.lua

* Remove superfluos /usr/local/lib path as it's default libc search patch. If
necessary one can supply custom search path via LD_LIBRARY_PATH environment
variable.
* Add correct LD_LIBRARY_PATH for busted tests.
* Do not supply library extension as this should be handled in LuaJit already.
Signed-off-by: Petr Štetiar <ynezz@true.cz>

Fix and improve loading of libtffi helper library

---

turbo/cdef.lua
turbo/platform.lua
turbo/syscall.lua

I just updated Turbolua to be able to run also on POWER architecture 64 bits.
Our team is still finishing the LuaJIT port to PPC64 so it's not on the official repository yet. Take a look at our Wiki hosted on GitHub for the latest status and for our code, if you want to check:
https://github.com/LuaJIT-PPC64/LuaJIT-PPC64/tree/ppc64-port
That LuaJIT is already functional and on Turbolua I was able to run some examples like the chatapp. If you have more tests that we can run on our PPC64 machine in order to find possible bugs, give us a hint please.

Port to PPC64

---

Makefile

Currently I'm ending up with a file /usr/bin which should be turbovisor

Create missing bin dir

---

turbo/iostream.lua

Remove one-off when determining if max_buffer_size was reached.
Fixes #232

Fix max_buffer_size condition in IOStream

---

.gitignore
Makefile
deps/turbo_ffi_wrap.c

In particular: fix `make SSL=none` by enclosing the #pragma pop within
the #ifndef TURBO_NO_SSL to prevent unknown pragmas warning with clang.
Also: skip `ldconfig` at uninstall time (Makefile).

OS X build improvements

---

turbo/web.lua

Return codes were inverted. We now have as expected:
* permanent -> HTTP 301
* temporary -> HTTP 302

turbo/web.lua: fix permanent/temporary redirect

---

turbo/escape.lua

This patch is implementation of method, proposed by jsolman from Issue #219

base64_encode: make insert newlines optional

---

turbo/cdef.lua
turbo/iostream.lua
turbo/socket_ffi.lua

When /etc/resolv.conf was changed (i.e. by new PPP connection), turbo is still using previously cached resolv.conf content (this  is a GLIBC feature).  Every connect trial fails with error:
` [async.lua] Error code -3. Could not resolve hostname 'myhostname.com': Temporary failure in name resolution`
Solution is to call res_init() function when getaddrinfo() return -3 (EAI_AGAIN).

iostream: reread resolv.conf if getaddrinfo() returns EAI_AGAIN

---

Makefile

LDFLAGS were not properly overriden during build with SSL
support. Specifying LDFLAGS as make argument caused no addition of
"-lcrypto -lssl".
Fix LDFLAGS override by specifying MYLDFLAGS helper variable.

Makefile: Fix overriding LDFLAGS

---

turbo/ioloop.lua

After running interval callback we issued set_last_call() on proecessed
interval. However, when we cleared interval inside its callback, we got
nil value inside _intervals table which caused indexing nil value during
set_last_call().
Assign Interval instanse to local variable, so we can safely issue
set_last_call() on it.

ioloop: Do not index cleared interval

---

turbo/httputil.lua

This is parsed correctly:
--161c49b7272a490316a30fa45caf6b289a52f22ec41cba17ecb2da8863f1
Content-Disposition: form-data; name="file"; filename="file.raw"
Content-Type: application/octet-stream
This is parsed wrong:
--0088a8ea4ce6f30e19b7cde5fbda1401d75bb49507f2a00e2993594b9b80
Content-Type: application/octet-stream
Content-Disposition: form-data; name="file"; filename="file.raw"
Field value "application/octet-stream" in second (wrong) case contains no ";" delimiter.
Turbo parses Content-Type value as "application/octet-stream\r\nContent-Disposition: form-data" which wrong.

Fix wrong parsing multipart form-data requests

---

turbo/httpserver.lua

keepalive client requests are getting closed, as requests
are always treated as HTTP/1.0. in code "headers.version"
is always comes as 'nil'. it is corrected to "headers:get_version()"

HTTPParser class does not has field named version

---

turbo/async.lua

#264 added persistent connections, however it seems a new socket was still opened even when there was no need for it

no need to open a new socket when reusing an existing one

---

turbo/cdef.lua

This patch allows using [luajit syscall](https://github.com/justincormack/ljsyscall) together with turbo in the same application.

avoid name clashes with ljsyscall

---

turbo/iostream.lua

if https server is run with luasocket and plain http request
is sent, results in high cpu usage. the reason is it keeps
trying to parse handshake request inspite of error

handle ssl handshake failure with luasocket

---

deps/http-parser/http_parser.c

This also suppresses -Wimplicit-fallthrough warning, which is enabled
in gcc7 by default.

http-parser: Fix typo in switch FALLTHROUGH comment

---

turbo/iostream.lua

When running httpserver.lua example and executing
'nmap localhost -p 8888' command we get error listed below.
After that it is no longer possible to handle HTTP requests.
[mniestroj@gm examples]$ luajit httpserver.lua
[E 2018/01/26 17:00:56] [ioloop.lua] Error in IOLoop handler.
▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
/usr/local/share/lua/5.1/turbo/iostream.lua:650: Error when reading from socket 5. Errno: 104. Connection reset by peer
stack traceback:
[C]: in function 'error'
/usr/local/share/lua/5.1/turbo/iostream.lua:650: in function '_read_from_socket'
/usr/local/share/lua/5.1/turbo/iostream.lua:725: in function '_read_to_buffer'
/usr/local/share/lua/5.1/turbo/iostream.lua:467: in function '_initial_read' …

iostream: Fix initial read for FFI sockets

---

turbo/async.lua

Context is https client connection with client certificates.
Previous code used wrong ssl options and called ssl_create_client_context with wrong parameter order.

Fixed broken client cert functionality

---

turbo/httputil.lua

This should pass the parameter as is.

httputil: do not error when parameter is incorrectly encoded

---

turbo/iostream.lua

When we are expecting next request (Connection: keep-alive) it is
possible '_initial_read()' will not gather any data because they are not
in the socket yet so expected HTTP header will not be found. Hence data
will be read to buffer from event handler. But in '_handle_read()' data
are read to buffer until EWOULDBLOCK appears before it calls
'_read_from_buffer()' again. So when request body is big it is possible
it will not fit into buffer which is prepared just for header size
(1024*18).
The solution is to call '_read_from_buffer()' every time when new data
are pushed to buffer.

Fix race condition in iostream.lua when using HTTPConnection

---

turbo/socket_ffi.lua

Because turbo has issues with #343 I have tried to use the lua socket option but found out it was broken.
It also looks like the lua socket option doesn't support http redirects?

socket_ffi.lua: correct luasocket variable name

---

deps/http-parser/.gitignore
deps/http-parser/.mailmap
deps/http-parser/.travis.yml
deps/http-parser/AUTHORS
deps/http-parser/LICENSE-MIT
deps/http-parser/Makefile
deps/http-parser/README.md
deps/http-parser/bench.c
deps/http-parser/contrib/parsertrace.c
deps/http-parser/contrib/url_parser.c
deps/http-parser/http_parser.c
deps/http-parser/http_parser.gyp
deps/http-parser/http_parser.h
deps/http-parser/test.c

Unless this contains breaking changes I'm not aware of, this updates `http-parser` dependency to the latest stable-with-patches, [v2.8.1](https://github.com/nodejs/http-parser/releases/tag/v2.8.1).
It builds OK, but I can't run the tests right now.

bump http-parser to v2.8.1

---

turbo/cdef.lua
turbo/syscall.lua

stat support was only available on Linux platform, while serving a static file requires fs.stat, which in turn invokes stat syscall, resulting in error "stdin:1: undeclared or implicit tag 'stat'"
This PR added stat support for osx (Darwin) so that serving static file works.

Add stat support for osx.

---

turbo/web.lua

turbo/web.lua: overwrite Content-Type header instead of adding new one when returning json
This change prevents the web server from returning 2 "Content-Type" headers instead of one
if a "Content-Type" header was already added as one of the default headers (in
turbo.web.RequestHandler:set_default_headers). Now there will be one Content-Type header at
most.
The reason is that it is useful to set as default header "Content-type: text/plain" when
you want to return that content (and not the default text/html) for 4xx and 5xx return codes
while returning json for 200. Without the present commit, in the happy path (200 return code),
the web server returned 2 Content-type headers (text/plain and application/json).

turbo/web.lua: overwrite Content-Type header instead of adding new one

---

examples/multipart.lua
turbo/httpserver.lua
turbo/httputil.lua
turbo/iostream.lua

isolated function which parse headers of multipart from parse_multipart_data() add kwargs.streaming_multipart_bytes in httpserver let user to parse multipart data in streaming and saved huge file (excess kwargs.large_body_bytes or 512 if no  setting) to /tmp
the 3x memory of files as instance:
file about 100M so the multipart/form-data body is about 100M
1. in `function iostream.IOStream:_read_to_buffer()` `self._read_buffer:append_right(ptr, sz)` would expand the buffer size to 100M
2. in `function iostream.IOStream:_consume(loc)` `chunk = ffi.string(ptr + self._read_buffer_offset, loc)` converting/coping c string to lua string takes 100M
3. in `function httputil.parse_multipart_data(data, boundary)` `argument[1] = data:sub(v1, b2)` slicing the huge file content as new string takes 100M …

implemented streaming parsing multipart/form-data as turbo takes 3x memory of uploading file(s) size during parsing multipart/form-data request
